exec systemctl --user import-environment WAYLAND_DISPLAY SWAYSOCK DISPLAY XCURSOR_THEME XCURSOR_SIZE
set $SYSTEMDRUN systemd-run --user --property=ExitType=cgroup --property=PartOf=graphical-session.target --collect --no-block --slice=app.slice --setenv=XDG_ACTIVATION_TOKEN --setenv=DESKTOP_STARTUP_ID
